### ISSUE TITLE
Plus distributions - general form

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#34]
We are wondering if it is possible on general grounds to reorganize something of this kind:

![r(z) + d \delta(z) + \sum_{k=0}^\infty c_k \left( \frac{\log^k(1-z)}{1-z} \right)_+](https://render.githubusercontent.com/render/math?math=r(z)%20%2B%20d%20%5Cdelta(z)%20%2B%20%5Csum_%7Bk%3D0%7D%5EN%20c_k(z)%20%5Cleft(%20%5Cfrac%7B%5Clog%5Ek(1-z)%7D%7B1-z%7D%20%5Cright)_%2B)

using constant coefficients for the distribution part:

![\tilde{r}(z) + \tilde{d} \delta(z) + \sum_{k=0}^\infty \tilde{c}_k \left( \frac{\log^k(1-z)}{1-z} \right)_+](https://render.githubusercontent.com/render/math?math=%5Ctilde%7Br%7D(z)%20%2B%20%5Ctilde%7Bd%7D%20%5Cdelta(z)%20%2B%20%5Csum_%7Bk%3D0%7D%5EN%20%5Ctilde%7Bc%7D_k%20%5Cleft(%20%5Cfrac%7B%5Clog%5Ek(1-z)%7D%7B1-z%7D%20%5Cright)_%2B)

If this is possible:
- we are thinking about rewriting our `DistributionVec` a little in order to collect all the singular bits in a single one (so we will have a fixed amount of components equal to 3 for all orders)
- just do this we only need to:
  - include in coefficient functions definition the `log(1-z) ** k / (1-z)`
  - multiply in the convolution just for the pdf difference `pdf(x/z)/z - pdf(x)`, that is available since what we currently are doing is multiplying each one of these two terms by a factor that is constant in the second expression (`\tilde{c}_k`)

**Comment by felixhekhorn** [comment]
done in #72
