### ISSUE TITLE
Testing with limited resources

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#41]
## Separate apfel cache
Since apfel is static (from the point view of its implementation) as long as we keep the same input there is no reason to rerun separately in every workflow, so we can store the cache somewhere accessible from the workflow.
The following two strategies (and a mixed one) are available for generation:
1. keep apfel cache across runs (so push back the one generated by workflows)
2. generate apfel cache somewhere else (e.g.: Milan cluster)

## Statistical approach
In order to keep the test size constant (or not growing exponentially with features), we can always run the test for isolated features, but selecting randomly only some combinations for each run, since there is no principle to decide a priori that some combination are more important than others.
- decide a fixed amount of *slots*
- decide some tests to be always run (e.g.: isolated features)
- attribute randomly the free *slots*
- keep logs of each random selection (for reproducibility and more)
- leave some hooks for adding more deterministic tests (e.g.: for running again failing ones)
- avoid most recent combinations in the random selection (for a quicker exploration)

**Comment by felixhekhorn** [comment]
use option 2 for the moment, i.e., use the cluster
