### ISSUE TITLE
Structure Functions unit tests

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#45]
Define unit tests for all `...StructureFunction`s classes and logic:
- `StructureFunction`
- `ESF`
- `ESFTMC`
- ...

Useful ideas:
- factorize base mocking for all needed classes
- use `pytest.monkeypatch` to fake intermediate object difficult to access (you can register functions/objects to be used in place of something else, even without entering inside)

**Comment by felixhekhorn** [comment]
closed almost by #96
