### ISSUE TITLE
Import external formula for coefficient functions

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#53]
In order to import external formulas, like ones in [vogt](https://www.liverpool.ac.uk/~avogt/coeff.html), that are usually encoded in small fortran functions, it would be a good a idea to download and collect them in a single 'external' folder, and write a Makefile to compile this folder in a corresponding one importable from python.

Than Makefile should provide an install command to install the new python importable coefficient functions' expressions in yadism package.

In the package everything should be organized as it is, but the ESF implementations (F2light, F2charm, ...) instead of defining themselves the coefficient functions should only import them.

**Comment by AleCandido** [comment]
We have a final answer to this issue:
**everything will be translated to python**

If anyone is interested in *"how to port fortran code to python"* we provided a definitive answer also for this question:
**by hand**
(the rationale is that fortran code involved is almost python code, in the sense that there is only math involved, so copy and paste it's really the least expensive way of porting)

The full structure for hosting coefficient functions has been set in #72.

**Comment by felixhekhorn** [comment]
translation done  in #110
