### ISSUE TITLE
More benchmarks

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#61]
- [x] Include benchmarks suggested by Juan Rojo, [see the wiki](https://github.com/N3PDF/yadism/wiki/Benchmarks-resources).
- [x] Include even more benchmarks, for example the code by Paolo Nason/Eric Laenen we discussed with Stefano C. (you can find it in https://github.com/nnpdf/external/tree/master/FONLLdis)
- [x] `xspace-bench`

**Comment by AleCandido** [comment]
Working on QCDNUM, still to be done:

- [ ] include & install QCDNUM python package
- [ ] upgrade navigator
- [ ] compare QCDNUM and find out numeric issues
- [ ] extend QCDNUM bindings (heavy flavors, and so on)

**Comment by felixhekhorn** [comment]
We give up on FONLLdis because it is too old, complicated and limited

**Comment by AleCandido** [comment]
Spurious minus sign surviving in F3bottom:
https://github.com/N3PDF/yadism/blob/develop/benchmarks/yadmark/benchmark/external/xspace_bench_utils.py#L197-L198

**Comment by felixhekhorn** [comment]
finished
