### ISSUE TITLE
Deliver in the Flavor basis

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#69]
In order to make things easy for the user the current setup is not the best one.

There are two basis involved:
1. the coefficient function basis: singlet, non-singlet, gluon
2. the pdf basis: flavor basis
and the weights are a bridge between them.

Since the first one is needed only for internal purpose we should:
- [x] apply weights internally (not showing them to the user)
- [x] ~~rotate the output in the flavor basis~~
  - maybe instead we should provide all the ingredients separately:
    - the coefficient functions vector (in their own basis: g, s, nsp, nsm)
    - the basis rotation (13x4 matrix)
    - the weights matrix (diagonal matrix of charges)

**Comment by felixhekhorn** [comment]
closed with #90
