### ISSUE TITLE
QED corrections

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/yadism#74]
- do we want to implement those?
- if yes: speak with Christopher

From the email exchange on 19.08.20 between SF, ERN, SC, CS, FH, AC we can already give two references
- "Factorized approach to radiative corrections for inelastic lepton-hadron collisions" https://arxiv.org/pdf/2008.02895.pdf 
- https://wiki.bnl.gov/eic/index.php/DJANGOH

**Comment by cschwan** [comment]
Just to reiterate what I said about EW corrections: [arxiv:2008.02895](https://arxiv.org/pdf/2008.02895.pdf) doesn't consider purely weak corrections. For instance imagine a box, where two t-channel W bosons connect the lepton and the quark fermion line and change the flavour of the quark and convert the lepton into a neutrino, and then back again into the old state.

**Comment by felixhekhorn** [comment]
- Yes, but they only claim to discuss QED corrections, so they are consistent
- Now the question is whether this is a good approximation to the *full* EW corrections - I guess this might depend on Q2, S, etc. (in their Fig. 2, you can basically swap all lines with W/Z)
- However, I guess one should maybe read the paper more carefully as I can see their point in the second paragraph: Q2 is by definition a QED variable - and this might become a problem ... maybe this issue isn't that easy to implement ... @cschwan or at least we would need to spend some time on the theory side ;-)

**Comment by AleCandido** [comment]
Not going to implement in this PhD/PostDoc (at least not in a year from now)

**Comment by cschwan** [comment]
There's a chance that SHERPA might be able to do it.
