### ISSUE TITLE
Split heavy quark masses

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#86]
At the moment the theory runcard is defining three kinds of heavy quark masses:
- `mc`: the mass of the charm (e.g.)
- `Qmc`: the reference scale at which `mc` is evaluated as a Lagrangian parameter in a renormalization scheme (say MSbar)
- `kcthr`: so the actual new mass is given by `kcthr * mc`, and it is the threshold used by any VFNS for charm

For `yadism` they all coincide currently, because:
- mass schemes other than `POLE` are not implemented (so `Qmc` is irrelevant)
- `kcthr` is always considered one

Let's fix at least the second, and we will deal with the first as soon as HQMS will be implemented.

**Comment by felixhekhorn** [comment]
part one is done in https://github.com/N3PDF/eko/pull/62, the difference between pole mass and MSbar mass is discussed in #84
